import Head from 'next/head';
import Image from 'next/image';
import Link from "next/link";
import styles from '../styles/Home.module.css';
import typingStyles from "../styles/typing.module.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from 'react-responsive-carousel';
import Footer from "./footer.js";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Ben Landon&apos;s Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<main className={styles.main}>
				<h1 className={styles.title}>
					<Link href="/">
						<a className={typingStyles.dropDown}>Ben Landon&apos;s Portfolio</a>
					</Link>
				</h1>
			
				<div className={styles.description}><p className={typingStyles.typedText}>A collection of all of my projects.</p></div>

				<Carousel autoPlay={true} infiniteLoop={true} interval={2000} className={styles.carousel} showStatus={false} stopOnHover={false} showThumbs={false} showArrows={false} showIndicators={false} axis={"horizontal"}>
					<Link href="https://github.com/https123456789/BFC">
						<div>
							<iframe src="/displayCard/BFC"></iframe>
						</div>
					</Link>
					<Link href="https://github.com/https123456789/Textual">
						<div>
							<iframe src="/displayCard/Textual"></iframe>
						</div>
					</Link>
					<Link href="https://github.com/https123456789/GithubAPI">
						<div>
							<iframe src="/displayCard/GithubAPI"></iframe>
						</div>
					</Link>
					<Link href="https://github.com/https123456789/Cube-Run">
						<div>
							<iframe src="/displayCard/Cube-Run"></iframe>
						</div>
					</Link>
					<Link href="https://github.com/https123456789/Cpp-Math">
						<div>
							<iframe src="/displayCard/Cpp-Math"></iframe>
						</div>
					</Link>
				</Carousel>
				
				<div className={styles.grid}>
					<a href="https://github.com/https123456789" className={styles.card}>
						<h2>
							<img src="/icons/github-mark.svg" alt="" className={styles.cardIcon}/>
							<p>My Github Page &rarr;</p>
						</h2>
						<p>Check out all of my open source projects.</p>
					</a>
			
					<a href="https://replit.com/@https123456789" className={styles.card}>
						<h2>
							<img src="/icons/replit-logo.svg" alt="" className={styles.cardIcon}/>
							<p>My Replit Page &rarr;</p>
						</h2>
						<p>Check out my projects on Replit.</p>
					</a>
				</div>
			</main>
			<Footer/>
		</div>
	)
}