name: Langs SVG Update CronJob
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */7 * *'

jobs:
  update_langs_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install wget
        run: sudo apt install wget

      - name: Download New Image
        run: 'wget "https://github-readme-stats-https123456789-personal-instance.vercel.app/api/top-langs?username=https123456789&hide_border=true&card_width=500&theme=github_dark&layout=donnut&langs_count=6&exclude_repo=github-readme-stats%2CImDaH%2Clandon-website%2CTextual%2CDrawer-Front-End&size_weight=0.6&count_weight=0.4&hide=HTML%2CCSS%2CBeef" -O langs.svg'

      - name: Commit
        uses: test-room-7/action-update-file@v1
        with:
            file-path: langs.svg
            commit-msg: 'cronjob(langs.yml): update langs.svg'
            github-token: ${{ secrets.GITHUB_TOKEN }}
