name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 */7 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
  snk:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
